version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blogpassword

  blog:
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/blog
    build: .