spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: blogpassword
  profiles:
    active: product

---
spring:
  profiles: product
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    prefix: "classpath:"
    enabled: true
server:
  port: 8080
  servlet:
    context-path: /blog


---

spring:
  profiles: test
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: false
